/* parser generated by jison 0.4.17 */
/*
  Returns a Parser object of the following structure:

  Parser: {
    yy: {}
  }

  Parser.prototype: {
    yy: {},
    trace: function(),
    symbols_: {associative list: name ==> number},
    terminals_: {associative list: number ==> name},
    productions_: [...],
    performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate, $$, _$),
    table: [...],
    defaultActions: {...},
    parseError: function(str, hash),
    parse: function(input),

    lexer: {
        EOF: 1,
        parseError: function(str, hash),
        setInput: function(input),
        input: function(),
        unput: function(str),
        more: function(),
        less: function(n),
        pastInput: function(),
        upcomingInput: function(),
        showPosition: function(),
        test_match: function(regex_match_array, rule_index),
        next: function(),
        lex: function(),
        begin: function(condition),
        popState: function(),
        _currentRules: function(),
        topState: function(),
        pushState: function(condition),

        options: {
            ranges: boolean           (optional: true ==> token location info will include a .range[] member)
            flex: boolean             (optional: true ==> flex-like lexing behaviour where the rules are tested exhaustively to find the longest match)
            backtrack_lexer: boolean  (optional: true ==> lexer regexes are tested in order and for each matching regex the action code is invoked; the lexer terminates the scan when a token is returned by the action code)
        },

        performAction: function(yy, yy_, $avoiding_name_collisions, YY_START),
        rules: [...],
        conditions: {associative list: name ==> set},
    }
  }


  token location info (@$, _$, etc.): {
    first_line: n,
    last_line: n,
    first_column: n,
    last_column: n,
    range: [start_number, end_number]       (where the numbers are indexes into the input string, regular zero-based)
  }


  the parseError function receives a 'hash' object with these members for lexer and parser errors: {
    text:        (matched text)
    token:       (the produced terminal token, if any)
    line:        (yylineno)
  }
  while parser (grammar) errors will also provide these members, i.e. parser errors deliver a superset of attributes: {
    loc:         (yylloc)
    expected:    (string describing the set of expected tokens)
    recoverable: (boolean: TRUE when the parser has a error recovery rule available for this particular error)
  }
*/
var operator = (function(){
var o=function(k,v,o,l){for(o=o||{},l=k.length;l--;o[k[l]]=v);return o},$V0=[1,8],$V1=[1,9],$V2=[1,10],$V3=[6,8],$V4=[1,18],$V5=[1,26],$V6=[1,27],$V7=[1,28],$V8=[1,29],$V9=[8,18],$Va=[1,48],$Vb=[1,40],$Vc=[1,41],$Vd=[1,42],$Ve=[1,43],$Vf=[1,44],$Vg=[1,47],$Vh=[1,67],$Vi=[1,68],$Vj=[1,66],$Vk=[1,63],$Vl=[1,64],$Vm=[1,65],$Vn=[1,62],$Vo=[6,8,18];
var parser = {trace: function trace() { },
yy: {},
symbols_: {"error":2,"ConfigEntry":3,"{":4,"ConfigList":5,"}":6,"Config":7,",":8,"ClassName":9,"Import":10,"Actions":11,"NAME":12,":":13,"JSONString":14,"IMPORT":15,"[":16,"ImportList":17,"]":18,"ACTION":19,"ActionList":20,"Action":21,"ActionKey":22,"ActionConfigList":23,"QUERY":24,"INSERT":25,"UPDATE":26,"DELETE":27,"ActionConfig":28,"UrlConfig":29,"MethodConfig":30,"ParametersConfig":31,"responseTypeConfig":32,"responseConverter":33,"JSONMember":34,"Properties":35,"PROPS":36,"PropertyList":37,"Property":38,"PropertyMemberList":39,"PropertyMember":40,"PropertyKey":41,"JSONValue":42,"TYPE":43,"DEFAULTVALUE":44,"STRING":45,"JSONNumber":46,"NUMBER":47,"JSONNullLiteral":48,"NULL":49,"JSONBooleanLiteral":50,"TRUE":51,"FALSE":52,"JSONText":53,"EOF":54,"JSONObject":55,"JSONArray":56,"BINDINGPROP":57,"JSONMemberList":58,"JSONElementList":59,"$accept":0,"$end":1},
terminals_: {2:"error",4:"{",6:"}",8:",",12:"NAME",13:":",15:"IMPORT",16:"[",18:"]",19:"ACTION",24:"QUERY",25:"INSERT",26:"UPDATE",27:"DELETE",29:"UrlConfig",30:"MethodConfig",31:"ParametersConfig",32:"responseTypeConfig",33:"responseConverter",36:"PROPS",43:"TYPE",44:"DEFAULTVALUE",45:"STRING",47:"NUMBER",49:"NULL",51:"TRUE",52:"FALSE",54:"EOF",57:"BINDINGPROP"},
productions_: [0,[3,3],[5,1],[5,3],[7,1],[7,1],[7,1],[9,3],[10,5],[17,1],[17,3],[11,5],[20,1],[20,3],[21,5],[22,1],[22,1],[22,1],[22,1],[23,1],[23,3],[28,1],[28,1],[28,1],[28,1],[28,1],[28,1],[35,5],[37,1],[37,3],[38,3],[39,1],[39,3],[40,3],[41,1],[41,1],[41,1],[14,1],[46,1],[48,1],[50,1],[50,1],[53,2],[42,1],[42,1],[42,1],[42,1],[42,1],[42,1],[42,1],[55,2],[55,3],[34,3],[34,3],[34,3],[58,1],[58,3],[56,2],[56,3],[59,1],[59,3]],
performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate /* action[1] */, $$ /* vstack */, _$ /* lstack */) {
/* this == yyval */

var $0 = $$.length - 1;
switch (yystate) {
case 1:

            return {
                class: aClass,
                serviceMethods: serviceMethods
            }
        
break;
case 7:

            aClass.name = $$[$0];
        
break;
case 8:

            aClass.import = $$[$0-1];
        
break;
case 9: case 12: case 28: case 59:
this.$ = [$$[$0]];
break;
case 10:
this.$=$$[$0-2];this.$.push($$[$0])
break;
case 13: case 29:
this.$=$$[$0-2];this.$.push($$[$0]);
break;
case 14:

            parserUtil.createQueryMethod(aClass, $$[$0-1]);
            var method = parserUtil.createQueryMethodService($$[$0-1]);
            serviceMethods.push(method);
        
break;
case 19: case 31: case 55:
this.$ = {}; this.$[$$[$0][0]] = $$[$0][1];
break;
case 20: case 32: case 56:
this.$ = $$[$0-2]; $$[$0-2][$$[$0][0]] = $$[$0][1];
break;
case 27:

            parserUtil.createFields(aClass, $$[$0-1]);
        
break;
case 30: case 51: case 58:
this.$ = $$[$0-1];
break;
case 33: case 52: case 53: case 54:
this.$ = [$$[$0-2], $$[$0]];
break;
case 37:
 // replace escaped characters with actual character
          this.$ = yytext.replace(/\\(\\|")/g, "$"+"1")
                     .replace(/\\n/g,'\n')
                     .replace(/\\r/g,'\r')
                     .replace(/\\t/g,'\t')
                     .replace(/\\v/g,'\v')
                     .replace(/\\f/g,'\f')
                     .replace(/\\b/g,'\b');
        
break;
case 38:
this.$ = Number(yytext);
break;
case 39:
this.$ = null;
break;
case 40:
this.$ = true;
break;
case 41:
this.$ = false;
break;
case 42:
return this.$ = $$[$0-1];
break;
case 50:
this.$ = {};
break;
case 57:
this.$ = [];
break;
case 60:
this.$ = $$[$0-2]; $$[$0-2].push($$[$0]);
break;
}
},
table: [{3:1,4:[1,2]},{1:[3]},{5:3,7:4,9:5,10:6,11:7,12:$V0,15:$V1,19:$V2},{6:[1,11],8:[1,12]},o($V3,[2,2]),o($V3,[2,4]),o($V3,[2,5]),o($V3,[2,6]),{13:[1,13]},{13:[1,14]},{13:[1,15]},{1:[2,1]},{7:16,9:5,10:6,11:7,12:$V0,15:$V1,19:$V2},{14:17,45:$V4},{16:[1,19]},{4:[1,20]},o($V3,[2,3]),o($V3,[2,7]),o([6,8,13,18],[2,37]),{14:22,17:21,45:$V4},{20:23,21:24,22:25,24:$V5,25:$V6,26:$V7,27:$V8},{8:[1,31],18:[1,30]},o($V9,[2,9]),{6:[1,32],8:[1,33]},o($V3,[2,12]),{13:[1,34]},{13:[2,15]},{13:[2,16]},{13:[2,17]},{13:[2,18]},o($V3,[2,8]),{14:35,45:$V4},o($V3,[2,11]),{21:36,22:25,24:$V5,25:$V6,26:$V7,27:$V8},{4:[1,37]},o($V9,[2,10]),o($V3,[2,13]),{12:$Va,14:46,23:38,28:39,29:$Vb,30:$Vc,31:$Vd,32:$Ve,33:$Vf,34:45,43:$Vg,45:$V4},{6:[1,49],8:[1,50]},o($V3,[2,19]),o($V3,[2,21]),o($V3,[2,22]),o($V3,[2,23]),o($V3,[2,24]),o($V3,[2,25]),o($V3,[2,26]),{13:[1,51]},{13:[1,52]},{13:[1,53]},o($V3,[2,14]),{12:$Va,14:46,28:54,29:$Vb,30:$Vc,31:$Vd,32:$Ve,33:$Vf,34:45,43:$Vg,45:$V4},{4:$Vh,14:58,16:$Vi,42:55,45:$V4,46:59,47:$Vj,48:56,49:$Vk,50:57,51:$Vl,52:$Vm,55:60,56:61,57:$Vn},{4:$Vh,14:58,16:$Vi,42:69,45:$V4,46:59,47:$Vj,48:56,49:$Vk,50:57,51:$Vl,52:$Vm,55:60,56:61,57:$Vn},{4:$Vh,14:58,16:$Vi,42:70,45:$V4,46:59,47:$Vj,48:56,49:$Vk,50:57,51:$Vl,52:$Vm,55:60,56:61,57:$Vn},o($V3,[2,20]),o($V3,[2,52]),o($Vo,[2,43]),o($Vo,[2,44]),o($Vo,[2,45]),o($Vo,[2,46]),o($Vo,[2,47]),o($Vo,[2,48]),o($Vo,[2,49]),o($Vo,[2,39]),o($Vo,[2,40]),o($Vo,[2,41]),o($Vo,[2,38]),{6:[1,71],12:$Va,14:46,34:73,43:$Vg,45:$V4,58:72},{4:$Vh,14:58,16:$Vi,18:[1,74],42:76,45:$V4,46:59,47:$Vj,48:56,49:$Vk,50:57,51:$Vl,52:$Vm,55:60,56:61,57:$Vn,59:75},o($V3,[2,53]),o($V3,[2,54]),o($Vo,[2,50]),{6:[1,77],8:[1,78]},o($V3,[2,55]),o($Vo,[2,57]),{8:[1,80],18:[1,79]},o($V9,[2,59]),o($Vo,[2,51]),{12:$Va,14:46,34:81,43:$Vg,45:$V4},o($Vo,[2,58]),{4:$Vh,14:58,16:$Vi,42:82,45:$V4,46:59,47:$Vj,48:56,49:$Vk,50:57,51:$Vl,52:$Vm,55:60,56:61,57:$Vn},o($V3,[2,56]),o($V9,[2,60])],
defaultActions: {11:[2,1],26:[2,15],27:[2,16],28:[2,17],29:[2,18]},
parseError: function parseError(str, hash) {
    if (hash.recoverable) {
        this.trace(str);
    } else {
        function _parseError (msg, hash) {
            this.message = msg;
            this.hash = hash;
        }
        _parseError.prototype = Error;

        throw new _parseError(str, hash);
    }
},
parse: function parse(input) {
    var self = this, stack = [0], tstack = [], vstack = [null], lstack = [], table = this.table, yytext = '', yylineno = 0, yyleng = 0, recovering = 0, TERROR = 2, EOF = 1;
    var args = lstack.slice.call(arguments, 1);
    var lexer = Object.create(this.lexer);
    var sharedState = { yy: {} };
    for (var k in this.yy) {
        if (Object.prototype.hasOwnProperty.call(this.yy, k)) {
            sharedState.yy[k] = this.yy[k];
        }
    }
    lexer.setInput(input, sharedState.yy);
    sharedState.yy.lexer = lexer;
    sharedState.yy.parser = this;
    if (typeof lexer.yylloc == 'undefined') {
        lexer.yylloc = {};
    }
    var yyloc = lexer.yylloc;
    lstack.push(yyloc);
    var ranges = lexer.options && lexer.options.ranges;
    if (typeof sharedState.yy.parseError === 'function') {
        this.parseError = sharedState.yy.parseError;
    } else {
        this.parseError = Object.getPrototypeOf(this).parseError;
    }
    function popStack(n) {
        stack.length = stack.length - 2 * n;
        vstack.length = vstack.length - n;
        lstack.length = lstack.length - n;
    }
    _token_stack:
        var lex = function () {
            var token;
            token = lexer.lex() || EOF;
            if (typeof token !== 'number') {
                token = self.symbols_[token] || token;
            }
            return token;
        };
    var symbol, preErrorSymbol, state, action, a, r, yyval = {}, p, len, newState, expected;
    while (true) {
        state = stack[stack.length - 1];
        if (this.defaultActions[state]) {
            action = this.defaultActions[state];
        } else {
            if (symbol === null || typeof symbol == 'undefined') {
                symbol = lex();
            }
            action = table[state] && table[state][symbol];
        }
                    if (typeof action === 'undefined' || !action.length || !action[0]) {
                var errStr = '';
                expected = [];
                for (p in table[state]) {
                    if (this.terminals_[p] && p > TERROR) {
                        expected.push('\'' + this.terminals_[p] + '\'');
                    }
                }
                if (lexer.showPosition) {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ':\n' + lexer.showPosition() + '\nExpecting ' + expected.join(', ') + ', got \'' + (this.terminals_[symbol] || symbol) + '\'';
                } else {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ': Unexpected ' + (symbol == EOF ? 'end of input' : '\'' + (this.terminals_[symbol] || symbol) + '\'');
                }
                this.parseError(errStr, {
                    text: lexer.match,
                    token: this.terminals_[symbol] || symbol,
                    line: lexer.yylineno,
                    loc: yyloc,
                    expected: expected
                });
            }
        if (action[0] instanceof Array && action.length > 1) {
            throw new Error('Parse Error: multiple actions possible at state: ' + state + ', token: ' + symbol);
        }
        switch (action[0]) {
        case 1:
            stack.push(symbol);
            vstack.push(lexer.yytext);
            lstack.push(lexer.yylloc);
            stack.push(action[1]);
            symbol = null;
            if (!preErrorSymbol) {
                yyleng = lexer.yyleng;
                yytext = lexer.yytext;
                yylineno = lexer.yylineno;
                yyloc = lexer.yylloc;
                if (recovering > 0) {
                    recovering--;
                }
            } else {
                symbol = preErrorSymbol;
                preErrorSymbol = null;
            }
            break;
        case 2:
            len = this.productions_[action[1]][1];
            yyval.$ = vstack[vstack.length - len];
            yyval._$ = {
                first_line: lstack[lstack.length - (len || 1)].first_line,
                last_line: lstack[lstack.length - 1].last_line,
                first_column: lstack[lstack.length - (len || 1)].first_column,
                last_column: lstack[lstack.length - 1].last_column
            };
            if (ranges) {
                yyval._$.range = [
                    lstack[lstack.length - (len || 1)].range[0],
                    lstack[lstack.length - 1].range[1]
                ];
            }
            r = this.performAction.apply(yyval, [
                yytext,
                yyleng,
                yylineno,
                sharedState.yy,
                action[1],
                vstack,
                lstack
            ].concat(args));
            if (typeof r !== 'undefined') {
                return r;
            }
            if (len) {
                stack = stack.slice(0, -1 * len * 2);
                vstack = vstack.slice(0, -1 * len);
                lstack = lstack.slice(0, -1 * len);
            }
            stack.push(this.productions_[action[1]][0]);
            vstack.push(yyval.$);
            lstack.push(yyval._$);
            newState = table[stack[stack.length - 2]][stack[stack.length - 1]];
            stack.push(newState);
            break;
        case 3:
            return true;
        }
    }
    return true;
}};

    var parserUtil = require('../parserUtil/operatorUtil');
    var aClass = parserUtil.createClass();
    var serviceMethods = [];
/* generated by jison-lex 0.3.4 */
var lexer = (function(){
var lexer = ({

EOF:1,

parseError:function parseError(str, hash) {
        if (this.yy.parser) {
            this.yy.parser.parseError(str, hash);
        } else {
            throw new Error(str);
        }
    },

// resets the lexer, sets new input
setInput:function (input, yy) {
        this.yy = yy || this.yy || {};
        this._input = input;
        this._more = this._backtrack = this.done = false;
        this.yylineno = this.yyleng = 0;
        this.yytext = this.matched = this.match = '';
        this.conditionStack = ['INITIAL'];
        this.yylloc = {
            first_line: 1,
            first_column: 0,
            last_line: 1,
            last_column: 0
        };
        if (this.options.ranges) {
            this.yylloc.range = [0,0];
        }
        this.offset = 0;
        return this;
    },

// consumes and returns one char from the input
input:function () {
        var ch = this._input[0];
        this.yytext += ch;
        this.yyleng++;
        this.offset++;
        this.match += ch;
        this.matched += ch;
        var lines = ch.match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno++;
            this.yylloc.last_line++;
        } else {
            this.yylloc.last_column++;
        }
        if (this.options.ranges) {
            this.yylloc.range[1]++;
        }

        this._input = this._input.slice(1);
        return ch;
    },

// unshifts one char (or a string) into the input
unput:function (ch) {
        var len = ch.length;
        var lines = ch.split(/(?:\r\n?|\n)/g);

        this._input = ch + this._input;
        this.yytext = this.yytext.substr(0, this.yytext.length - len);
        //this.yyleng -= len;
        this.offset -= len;
        var oldLines = this.match.split(/(?:\r\n?|\n)/g);
        this.match = this.match.substr(0, this.match.length - 1);
        this.matched = this.matched.substr(0, this.matched.length - 1);

        if (lines.length - 1) {
            this.yylineno -= lines.length - 1;
        }
        var r = this.yylloc.range;

        this.yylloc = {
            first_line: this.yylloc.first_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.first_column,
            last_column: lines ?
                (lines.length === oldLines.length ? this.yylloc.first_column : 0)
                 + oldLines[oldLines.length - lines.length].length - lines[0].length :
              this.yylloc.first_column - len
        };

        if (this.options.ranges) {
            this.yylloc.range = [r[0], r[0] + this.yyleng - len];
        }
        this.yyleng = this.yytext.length;
        return this;
    },

// When called from action, caches matched text and appends it on next action
more:function () {
        this._more = true;
        return this;
    },

// When called from action, signals the lexer that this rule fails to match the input, so the next matching rule (regex) should be tested instead.
reject:function () {
        if (this.options.backtrack_lexer) {
            this._backtrack = true;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. You can only invoke reject() in the lexer when the lexer is of the backtracking persuasion (options.backtrack_lexer = true).\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });

        }
        return this;
    },

// retain first n characters of the match
less:function (n) {
        this.unput(this.match.slice(n));
    },

// displays already matched input, i.e. for error messages
pastInput:function () {
        var past = this.matched.substr(0, this.matched.length - this.match.length);
        return (past.length > 20 ? '...':'') + past.substr(-20).replace(/\n/g, "");
    },

// displays upcoming input, i.e. for error messages
upcomingInput:function () {
        var next = this.match;
        if (next.length < 20) {
            next += this._input.substr(0, 20-next.length);
        }
        return (next.substr(0,20) + (next.length > 20 ? '...' : '')).replace(/\n/g, "");
    },

// displays the character position where the lexing error occurred, i.e. for error messages
showPosition:function () {
        var pre = this.pastInput();
        var c = new Array(pre.length + 1).join("-");
        return pre + this.upcomingInput() + "\n" + c + "^";
    },

// test the lexed token: return FALSE when not a match, otherwise return token
test_match:function (match, indexed_rule) {
        var token,
            lines,
            backup;

        if (this.options.backtrack_lexer) {
            // save context
            backup = {
                yylineno: this.yylineno,
                yylloc: {
                    first_line: this.yylloc.first_line,
                    last_line: this.last_line,
                    first_column: this.yylloc.first_column,
                    last_column: this.yylloc.last_column
                },
                yytext: this.yytext,
                match: this.match,
                matches: this.matches,
                matched: this.matched,
                yyleng: this.yyleng,
                offset: this.offset,
                _more: this._more,
                _input: this._input,
                yy: this.yy,
                conditionStack: this.conditionStack.slice(0),
                done: this.done
            };
            if (this.options.ranges) {
                backup.yylloc.range = this.yylloc.range.slice(0);
            }
        }

        lines = match[0].match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno += lines.length;
        }
        this.yylloc = {
            first_line: this.yylloc.last_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.last_column,
            last_column: lines ?
                         lines[lines.length - 1].length - lines[lines.length - 1].match(/\r?\n?/)[0].length :
                         this.yylloc.last_column + match[0].length
        };
        this.yytext += match[0];
        this.match += match[0];
        this.matches = match;
        this.yyleng = this.yytext.length;
        if (this.options.ranges) {
            this.yylloc.range = [this.offset, this.offset += this.yyleng];
        }
        this._more = false;
        this._backtrack = false;
        this._input = this._input.slice(match[0].length);
        this.matched += match[0];
        token = this.performAction.call(this, this.yy, this, indexed_rule, this.conditionStack[this.conditionStack.length - 1]);
        if (this.done && this._input) {
            this.done = false;
        }
        if (token) {
            return token;
        } else if (this._backtrack) {
            // recover context
            for (var k in backup) {
                this[k] = backup[k];
            }
            return false; // rule action called reject() implying the next rule should be tested instead.
        }
        return false;
    },

// return next match in input
next:function () {
        if (this.done) {
            return this.EOF;
        }
        if (!this._input) {
            this.done = true;
        }

        var token,
            match,
            tempMatch,
            index;
        if (!this._more) {
            this.yytext = '';
            this.match = '';
        }
        var rules = this._currentRules();
        for (var i = 0; i < rules.length; i++) {
            tempMatch = this._input.match(this.rules[rules[i]]);
            if (tempMatch && (!match || tempMatch[0].length > match[0].length)) {
                match = tempMatch;
                index = i;
                if (this.options.backtrack_lexer) {
                    token = this.test_match(tempMatch, rules[i]);
                    if (token !== false) {
                        return token;
                    } else if (this._backtrack) {
                        match = false;
                        continue; // rule action called reject() implying a rule MISmatch.
                    } else {
                        // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
                        return false;
                    }
                } else if (!this.options.flex) {
                    break;
                }
            }
        }
        if (match) {
            token = this.test_match(match, rules[index]);
            if (token !== false) {
                return token;
            }
            // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
            return false;
        }
        if (this._input === "") {
            return this.EOF;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. Unrecognized text.\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });
        }
    },

// return next match that has a token
lex:function lex() {
        var r = this.next();
        if (r) {
            return r;
        } else {
            return this.lex();
        }
    },

// activates a new lexer condition state (pushes the new lexer condition state onto the condition stack)
begin:function begin(condition) {
        this.conditionStack.push(condition);
    },

// pop the previously active lexer condition state off the condition stack
popState:function popState() {
        var n = this.conditionStack.length - 1;
        if (n > 0) {
            return this.conditionStack.pop();
        } else {
            return this.conditionStack[0];
        }
    },

// produce the lexer rule set which is active for the currently active lexer condition state
_currentRules:function _currentRules() {
        if (this.conditionStack.length && this.conditionStack[this.conditionStack.length - 1]) {
            return this.conditions[this.conditionStack[this.conditionStack.length - 1]].rules;
        } else {
            return this.conditions["INITIAL"].rules;
        }
    },

// return the currently active lexer condition state; when an index argument is provided it produces the N-th previous condition state, if available
topState:function topState(n) {
        n = this.conditionStack.length - 1 - Math.abs(n || 0);
        if (n >= 0) {
            return this.conditionStack[n];
        } else {
            return "INITIAL";
        }
    },

// alias for begin(condition)
pushState:function pushState(condition) {
        this.begin(condition);
    },

// return the number of states currently on the stack
stateStackSize:function stateStackSize() {
        return this.conditionStack.length;
    },
options: {},
performAction: function anonymous(yy,yy_,$avoiding_name_collisions,YY_START) {
var YYSTATE=YY_START;
switch($avoiding_name_collisions) {
case 0:/* skip whitespace */
break;
case 1:return 15
break;
case 2:return 'VIEWMODELS'
break;
case 3:return 'CONTENT'
break;
case 4:yy_.yytext = yy_.yytext.substr(1,yy_.yyleng-2); return 'UNITS'
break;
case 5:yy_.yytext = yy_.yytext.substr(1,yy_.yyleng-2); return 'EVENT'
break;
case 6:yy_.yytext = yy_.yytext.substr(1,yy_.yyleng-2); return 'BIND'
break;
case 7:yy_.yytext = yy_.yytext.substr(1,yy_.yyleng-2); return 43
break;
case 8:yy_.yytext = yy_.yytext.substr(1,yy_.yyleng-2); return 12
break;
case 9:yy_.yytext = yy_.yytext.substr(1,yy_.yyleng-2); return 'INIT'
break;
case 10:yy_.yytext = yy_.yytext.substr(1,yy_.yyleng-2); return 57
break;
case 11:return 'FUNCTION'
break;
case 12:yy_.yytext = yy_.yytext.substr(1,yy_.yyleng-2); return 36
break;
case 13:yy_.yytext = yy_.yytext.substr(1,yy_.yyleng-2); return 44
break;
case 14:yy_.yytext = yy_.yytext.substr(1,yy_.yyleng-2); return 19
break;
case 15:yy_.yytext = yy_.yytext.substr(1,yy_.yyleng-2); return 24
break;
case 16:yy_.yytext = yy_.yytext.substr(1,yy_.yyleng-2); return 25
break;
case 17:yy_.yytext = yy_.yytext.substr(1,yy_.yyleng-2); return 26
break;
case 18:yy_.yytext = yy_.yytext.substr(1,yy_.yyleng-2); return 27
break;
case 19:return 47
break;
case 20:yy_.yytext = yy_.yytext.substr(1,yy_.yyleng-2); return 45
break;
case 21:return 4
break;
case 22:return 6
break;
case 23:return 16
break;
case 24:return 18
break;
case 25:return 8
break;
case 26:return 13
break;
case 27:return 51
break;
case 28:return 52
break;
case 29:return 49
break;
case 30:return 54
break;
case 31:return 'INVALID'
break;
}
},
rules: [/^(?:\s+)/,/^(?:"import")/,/^(?:"viewModels")/,/^(?:"content")/,/^(?:"units")/,/^(?:"event")/,/^(?:"bind")/,/^(?:"type")/,/^(?:"name")/,/^(?:"init")/,/^(?:"@\{.*\}")/,/^(?:function\s*\(\)\s*\{\s*.*?\s*\})/,/^(?:"properties")/,/^(?:"defaultValue")/,/^(?:"action")/,/^(?:"query")/,/^(?:"insert")/,/^(?:"update")/,/^(?:"delete")/,/^(?:(-?([0-9]|[1-9][0-9]+))(\.[0-9]+)?([eE][-+]?[0-9]+)?\b)/,/^(?:"(?:\\[\\"bfnrt\/]|\\u[a-fA-F0-9]{4}|[^\\\0-\x09\x0a-\x1f"])*")/,/^(?:\{)/,/^(?:\})/,/^(?:\[)/,/^(?:\])/,/^(?:,)/,/^(?::)/,/^(?:true\b)/,/^(?:false\b)/,/^(?:null\b)/,/^(?:$)/,/^(?:.)/],
conditions: {"INITIAL":{"rules":[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31],"inclusive":true}}
});
return lexer;
})();
parser.lexer = lexer;
function Parser () {
  this.yy = {};
}
Parser.prototype = parser;parser.Parser = Parser;
return new Parser;
})();


if (typeof require !== 'undefined' && typeof exports !== 'undefined') {
exports.parser = operator;
exports.Parser = operator.Parser;
exports.parse = function () { return operator.parse.apply(operator, arguments); };
exports.main = function commonjsMain(args) {
    if (!args[1]) {
        console.log('Usage: '+args[0]+' FILE');
        process.exit(1);
    }
    var source = require('fs').readFileSync(require('path').normalize(args[1]), "utf8");
    return exports.parser.parse(source);
};
if (typeof module !== 'undefined' && require.main === module) {
  exports.main(process.argv.slice(1));
}
}